export const SESSION_SECRET = 'session secret'
export const DB_HOST ='localhost'
export const DB_USER = 'root'
export const DB_PASSWORD = ''
export const DB_DATABASE='test_generator'
export const CORS_ORIGIN='http://localhost:3000'
